name: Pester Tests

on:
  push:
    branches:
      - main
      - development  # Add the development branch here
  pull_request:
    branches:
      - main
      - development  # Add the development branch here

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set TEMP environment variable
        run: |
          echo "TEMP=$env:TEMP" >> $env:GITHUB_ENV

      - name: Install Pester
        run: Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Run Pester tests
        run: powershell -ExecutionPolicy Bypass -Command "Invoke-Pester -Path .\Tests\ -Output Detailed"